### ISSUE TITLE
编译 framework 出错

### ISSUE THREAD

**Issue by chezhe** [leancloud/objc-sdk#488]
版本：11.0.0
错误信息如下：
```
/Users/de/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
	from /Users/de/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from build-framework.rb:8:in `<main>'
```

**Comment by chezhe** [comment]
请忽略。我不懂ruby，原来是缺少gem
